name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job_1:
    name: Tester
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest-reportlog
        python -m pip install matplotlib
        python -m pip install datetime
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test
      id: test
      run: |
        cd tz_2
        pytest tester.py -q --report-log=rez.json
  job_2:
    name: Sender
    needs: job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download math result for job 1
      uses: actions/download-artifact@v3
      with:
          name: rez
    - name: send telegram 
      uses: appleboy/telegram-action@master
      with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_KEY }}
          document: rez.json
  
