name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job_1:
    name: Tester
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest-reportlog
        python -m pip install matplotlib
        python -m pip install datetime
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test
      id: test
      run: |
        cd tz_2
        pytest tester.py -v
